# Generated by Django 5.1.3 on 2024-11-21 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_customuser_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'can view the book'), ('can_create', 'can create a book'), ('can_edit', 'can edit a book'), ('can_delete', 'can delete a book')]},
        ),
    ]
